/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SspDef"
 * 	found in "ssp.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types`
 */

#ifndef	_Asn1cStdTest_H_
#define	_Asn1cStdTest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <PrintableString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Asn1cStdTest */
typedef struct Asn1cStdTest {
	BOOLEAN_t	 btest1;
	long	 itest2;
	PrintableString_t	 assServerAccPointRef;
	BOOLEAN_t	 btest2;
	PrintableString_t	 assAuthPara;
	BOOLEAN_t	 btest3;
	long	 itest1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Asn1cStdTest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Asn1cStdTest;

#ifdef __cplusplus
}
#endif

#endif	/* _Asn1cStdTest_H_ */
