/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SspDef"
 * 	found in "ssp.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types`
 */

#include <asn_internal.h>

#include "Asn1cStdTest.h"

static int
memb_itest2_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 12)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_itest2_constr_3 = {
	{ APC_CONSTRAINED,	 4,  4,  0,  12 }	/* (0..12) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 }
};
static asn_TYPE_member_t asn_MBR_Asn1cStdTest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Asn1cStdTest, btest1),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"btest1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Asn1cStdTest, itest2),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		memb_itest2_constraint_1,
		&asn_PER_memb_itest2_constr_3,
		0,
		"itest2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Asn1cStdTest, assServerAccPointRef),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"assServerAccPointRef"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Asn1cStdTest, btest2),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"btest2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Asn1cStdTest, assAuthPara),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"assAuthPara"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Asn1cStdTest, btest3),
		(ASN_TAG_CLASS_UNIVERSAL | (1 << 2)),
		0,
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"btest3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Asn1cStdTest, itest1),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"itest1"
		},
};
static ber_tlv_tag_t asn_DEF_Asn1cStdTest_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Asn1cStdTest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 0, 0, 2 }, /* btest1 at 4 */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 3, -1, 1 }, /* btest2 at 7 */
    { (ASN_TAG_CLASS_UNIVERSAL | (1 << 2)), 5, -2, 0 }, /* btest3 at 9 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 1 }, /* itest2 at 5 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 6, -1, 0 }, /* itest1 at 11 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 2, 0, 1 }, /* assServerAccPointRef at 6 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 4, -1, 0 } /* assAuthPara at 8 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Asn1cStdTest_specs_1 = {
	sizeof(struct Asn1cStdTest),
	offsetof(struct Asn1cStdTest, _asn_ctx),
	asn_MAP_Asn1cStdTest_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Asn1cStdTest = {
	"Asn1cStdTest",
	"Asn1cStdTest",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Asn1cStdTest_tags_1,
	sizeof(asn_DEF_Asn1cStdTest_tags_1)
		/sizeof(asn_DEF_Asn1cStdTest_tags_1[0]), /* 1 */
	asn_DEF_Asn1cStdTest_tags_1,	/* Same as above */
	sizeof(asn_DEF_Asn1cStdTest_tags_1)
		/sizeof(asn_DEF_Asn1cStdTest_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Asn1cStdTest_1,
	7,	/* Elements count */
	&asn_SPC_Asn1cStdTest_specs_1	/* Additional specs */
};

