/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SspDef"
 * 	found in "ssp.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types`
 */

#include <asn_internal.h>

#include "ReqAss.h"

static asn_TYPE_member_t asn_MBR_ReqAss_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReqAss, assServerAccPointRef),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"assServerAccPointRef"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReqAss, assPduSize),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"assPduSize"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReqAss, assAuthPara),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"assAuthPara"
		},
};
static ber_tlv_tag_t asn_DEF_ReqAss_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReqAss_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* assPduSize at 24 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 0, 0, 1 }, /* assServerAccPointRef at 23 */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 2, -1, 0 } /* assAuthPara at 25 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReqAss_specs_1 = {
	sizeof(struct ReqAss),
	offsetof(struct ReqAss, _asn_ctx),
	asn_MAP_ReqAss_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReqAss = {
	"ReqAss",
	"ReqAss",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	SEQUENCE_decode_aper,
	SEQUENCE_encode_aper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReqAss_tags_1,
	sizeof(asn_DEF_ReqAss_tags_1)
		/sizeof(asn_DEF_ReqAss_tags_1[0]), /* 1 */
	asn_DEF_ReqAss_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReqAss_tags_1)
		/sizeof(asn_DEF_ReqAss_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ReqAss_1,
	3,	/* Elements count */
	&asn_SPC_ReqAss_specs_1	/* Additional specs */
};

