/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SspDef"
 * 	found in "ssp.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types`
 */

#ifndef	_ReqGetObjectClass_H_
#define	_ReqGetObjectClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReqGetObjectClass */
typedef long	 ReqGetObjectClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReqGetObjectClass;
asn_struct_free_f ReqGetObjectClass_free;
asn_struct_print_f ReqGetObjectClass_print;
asn_constr_check_f ReqGetObjectClass_constraint;
ber_type_decoder_f ReqGetObjectClass_decode_ber;
der_type_encoder_f ReqGetObjectClass_encode_der;
xer_type_decoder_f ReqGetObjectClass_decode_xer;
xer_type_encoder_f ReqGetObjectClass_encode_xer;
per_type_decoder_f ReqGetObjectClass_decode_uper;
per_type_encoder_f ReqGetObjectClass_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ReqGetObjectClass_H_ */
