/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SspDef"
 * 	found in "ssp.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types`
 */

#ifndef	_ResAssOK_H_
#define	_ResAssOK_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include "ResErr.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResAssOK */
typedef struct ResAssOK {
	OCTET_STRING_t	 assId;
	long	 assPduSize;
	ResErr_t	 reserr;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResAssOK_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResAssOK;

#ifdef __cplusplus
}
#endif

#endif	/* _ResAssOK_H_ */
