/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SspDef"
 * 	found in "ssp.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types`
 */

#ifndef	_ResErr_H_
#define	_ResErr_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ResErr */
typedef long	 ResErr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ResErr;
asn_struct_free_f ResErr_free;
asn_struct_print_f ResErr_print;
asn_constr_check_f ResErr_constraint;
ber_type_decoder_f ResErr_decode_ber;
der_type_encoder_f ResErr_encode_der;
xer_type_decoder_f ResErr_decode_xer;
xer_type_encoder_f ResErr_encode_xer;
per_type_decoder_f ResErr_decode_uper;
per_type_encoder_f ResErr_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ResErr_H_ */
