/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "SspDef"
 * 	found in "ssp.asn1"
 * 	`asn1c -S skeletons -fskeletons-copy -fnative-types`
 */

#ifndef	_StrRef_H_
#define	_StrRef_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StrRef */
typedef PrintableString_t	 StrRef_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StrRef;
asn_struct_free_f StrRef_free;
asn_struct_print_f StrRef_print;
asn_constr_check_f StrRef_constraint;
ber_type_decoder_f StrRef_decode_ber;
der_type_encoder_f StrRef_encode_der;
xer_type_decoder_f StrRef_decode_xer;
xer_type_encoder_f StrRef_encode_xer;
per_type_decoder_f StrRef_decode_uper;
per_type_encoder_f StrRef_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _StrRef_H_ */
